app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager
from datetime import datetime



class User(UserMixin, db.Model):
    """
    Create an User table
    """
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    full_name = db.Column(db.String(60), index=True)
    password_hash = db.Column(db.String(128))
    position = db.Column(db.String(60), index=True)

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"User('{self.id}','{self.email}','{self.username}', '{self.full_name}', '{self.position}')"
    
# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Minutes(db.Model):
    """
    Create an minutes table
    """
    __tablename__ = "minutes"

    minute_id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), index=True)
    created_by = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    name_of_org = db.Column(db.String(60), index=True, default="analog")
    purpose = db.Column(db.String(60), index=True)
    body = db.Column(db.Text)
    attendees = db.Column(db.String(60), index=True)
    date_created = db.Column(db.DateTime(), default=datetime.utcnow)
    date_modified = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)
    
   
    def _repr_(self):
        return f"Minutes('{self.id}', '{self.title}', '{self.body}', '{self.created_by}','{self.name_of_org}', '{self.purpose}', '{self.date_created}', '{self.date_modified}', '{self.attendees}')"

app/__init__.py
# app/__init__.py
from flask import Flask

from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
import pymysql

pymysql.install_as_MySQLdb()

# local imports
from config import app_config

# db variable initialization
db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    db.init_app(app)

    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"

    migrate = Migrate(app, db)

    from app import models

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .notes import notes as notes_blueprint
    app.register_blueprint(notes_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py
from flask_login import login_required, current_user
from flask import flash, redirect, render_template, url_for, request, redirect
from . import home
from ..models import User, Minutes
from app import db
from datetime import datetime

@home.route('/')
@home.route('/home')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    notes = Minutes.query.join(User).add_columns(Minutes.title, Minutes.minute_id, Minutes.purpose, Minutes.name_of_org, User.full_name).all()

    return render_template('dashboard.html', title="Dashboard", notes = notes)

@home.route('/handle_data', methods=["GET", "POST"])
@login_required
def handle_data():
    
    title = request.form.get("title")
    body = request.form.get("body")
    org = request.form.get("org")
    purpose = request.form.get("purpose")
    attendees = request.form.get("attendees")
    user = current_user.get_id()
    # user = session["user_id"]
    minute = Minutes(body = body, name_of_org =org, purpose = purpose, 
                    attendees = attendees, created_by = user, title=title)
    db.session.add(minute)
    db.session.commit()
    flash("You have create a note")

    return redirect(url_for('home.dashboard'))

@home.route('/search', methods = ["POST"])
@login_required
def search_results():
    search_string = request.form.get("search1")
    filter = request.form.get("filters")
    if search_string:
        if filter == 'name_of_org':
            notes = Minutes.query.join(User).add_columns(Minutes.title, Minutes.minute_id, Minutes.purpose, 
            Minutes.name_of_org, User.full_name).filter(Minutes.name_of_org.contains(search_string)).all()
        elif filter == 'purpose':
            notes = Minutes.query.join(User).add_columns(Minutes.title, Minutes.minute_id, Minutes.purpose, 
            Minutes.name_of_org, User.full_name).filter(Minutes.purpose.contains(search_string)).all()
        elif filter == 'attendees':
            notes = Minutes.query.join(User).add_columns(Minutes.title, Minutes.minute_id, Minutes.purpose, 
            Minutes.name_of_org, User.full_name).filter(Minutes.attendees.contains(search_string)).all()
        elif filter == 'date_created':
            date = datetime.strptime(search_string, '%d/%m/%y')
            notes = Minutes.query.join(User).add_columns(Minutes.title, Minutes.minute_id, Minutes.purpose, 
            Minutes.name_of_org, User.full_name).filter(Minutes.date_created.contains(date)).all()       
        else:
            notes = Minutes.query.join(User).add_columns(Minutes.title, Minutes.minute_id, Minutes.purpose, 
            Minutes.name_of_org, User.full_name).all()
    else:
        notes = Minutes.query.join(User).add_columns(Minutes.title, Minutes.minute_id, Minutes.purpose, 
        Minutes.name_of_org, User.full_name).all()
    return render_template('results.html', notes = notes)
   

app/notes/__init__.py
from flask import Blueprint

notes = Blueprint('notes', __name__)

from . import views

app/notes/views.py
from flask_login import login_required
from flask import flash, redirect, render_template, url_for, request, redirect
from . import notes
from ..models import User, Minutes
from app import db
from datetime import datetime
from .edit_form import EditForm





@notes.route('/note/<int:n_id>', methods=["GET"])
@login_required
def view_note(n_id):
    note = Minutes.query.join(User).add_columns(Minutes.created_by,Minutes.body,Minutes.title, Minutes.purpose, Minutes.minute_id, Minutes.name_of_org, Minutes.attendees, Minutes.date_created, Minutes.date_modified, User.full_name).filter(Minutes.minute_id == n_id).first()
    user = User.query.add_column(User.full_name).filter_by(id=note.created_by)
    create = note.date_created.strftime("%d of %B %Y on %A at %I:%M %p")
    modified = note.date_modified.strftime("%d of %B %Y on %A at %I:%M %p")
    
    return render_template("note.html", note = note, modified=modified, user=user,create = create)

@notes.route('/delete/<int:d_id>', methods=['GET'])
@login_required
def delete_note(d_id):
    minute = Minutes.query.filter_by(minute_id=d_id).first()
    db.session.delete(minute)
    db.session.commit()
    flash('You have successfully deleted a note')

    # redirect to the departments page
    return redirect(url_for('home.dashboard'))

@notes.route("/edit/<int:e_id>", methods=["GET", "POST"])
@login_required
def edit_note(e_id):
    note = Minutes.query.filter(Minutes.minute_id==e_id).first()
    note_dict = {"title": note.title, "body": note.body,"minute_id": note.minute_id, "attendees": note.attendees, "purpose": note.purpose, "name_of_org": note.name_of_org}
    form = EditForm(data=note_dict)
    
    if request.method == "POST":
        note.title = form.title.data
        note.purpose = form.purpose.data
        note.name_of_org = form.name_of_org.data
        note.attendees = form.attendees.data
        note.body = form.body.data
        db.session.commit()
        flash('You have successfully edited the note.')

        # redirect to the departments page
        return redirect(url_for('notes.view_note',n_id=note.minute_id))
        
    
            
    return render_template('edit_form.html', action="Edit",note=note, form=form,title="Edit Note")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Analog </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Okobiah Ogheneyoma">
    <!--Bootstrap link-->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
   
</head>
<body>
    <div id="app">
        <nav>
         <ul class="menu">
             <li class="logo"> <a href="/home"><img src="/static/images/ANALOG.png"/></a> </li>
             <li class="item button"> <a href="/home">Home</a> </li>
             <li class="item button"> <a href="/login">Login</a> </li>
             <li class="item button"> <a href="/signup">Sign Up</a> </li>
         </ul>  
        </nav>
    </div>  
      <br>
    
        {% block body %}
        {% endblock %}
        
      
  <footer>&copy;2020 ANALOG. All Rights Reserved</footer>
  
    
</body>
</html>

app/templates/dashboard.html
<!DOCTYPE HTML>
<html>
<head>
        <title>Dashboard</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
   

</head>
<body>

    <div id="app">
	<nav>
     <ul class="menu">
         <li class="logo"> <a><img src="/static/images/ANALOG.png"/></a> </li>
         <li class="item button"> <a href="/logout"><img style="width: 34px;" src="/static/images/human.png"></a>  </li>
     </ul>  
    </nav>

    <div class="row">
        <div class="column">

<div style="background-color: #5DEBE2; padding: 23px;">
  <form action="/search" method="POST">
      <!--surround the select box with a "custom-select" DIV element. Remember to set the width:-->
      <div class="custom-select" style="width:200px;">
        <select name="filters">
          <option value="0">Select filter:</option>
          <option value="date_created">Date</option>
          <option value="name_of_org">Organisation</option>
          <option value="purpose">Purpose</option>
          <option value="attendees">Attendees</option>
        </select>
      </div>



      <div class="wrap">
            <div class="search">
              <input name ="search1" type="text" class="searchTerm" placeholder="What are you looking for?">
              <button type="submit" class="searchButton">
                <!-- <i class="fa fa-search"></i> -->
                <img class="searchicon" src="/static/images/search.png"/>
              </button>
            
            </div>
            
      </div>
      <p style="color:gray; font-size: 12px;"> Note: For date enter in format day/month/year. Example 01/06/20; 1st June 2020.</p>

  </form>
</div>

<div style="background-color: #5DEBE2; padding: 10px; margin-top: 34px;">
        <div class="second1">
                
          <div class="row">
            {% for note in notes %}
            <div class="col-75" style="background-color: white;">
              
              <div><p style="padding-left:5px; padding-top: 5px;">Title: {{ note.title }} <br>Purpose: {{ note.purpose }} <br> Written by: {{ note.full_name }}</p></div>
              <br>
              <p style="padding-left: 5px; padding-bottom: 5px;"><a   href="{{ url_for('notes.view_note',n_id=note.minute_id) }}"> <button style="border:2px solid #5DEBE2; width: 100px; font-size: 15px;">View</button> </a> <a href="{{ url_for('notes.edit_note',e_id=note.minute_id) }}"><button style="border: 2px solid #5DEBE2; width: 100px; font-size: 15px;">Edit</button></a>   <a href="{{ url_for('notes.delete_note',d_id=note.minute_id) }}"><button style="border: 2px solid #5DEBE2; width: 100px; font-size: 15px;">Delete</button></a></p>
            </div>
            {% endfor %}
          </div>
        </div>              
</div>

        </div>
        <div class="column" >
            <div class="second">
                    <form action="{{ url_for('home.handle_data') }}" method="post">
                        <div class="row">
                          <div class="col-755">
                            <input type="text" id="fname" name="title" placeholder="Title">
                          </div>
                        </div>
                        <div class="row">
                          
                          <div class="col-755">
                            <input type="text" id="lname" name="purpose" placeholder="Purpose">
                          </div>
                        </div>
                        <div class="row">
                          
                                <div class="col-755">
                                  <input type="text" id="lname" name="name_of_org" placeholder="organisation">
                                </div>
                              </div>
                              <div class="row">
                          
                                    <div class="col-755">
                                      <input type="text" id="lname" name="attendees" placeholder="Attendees">
                                    </div>
                                  </div>
                        <div class="row">
                          
                          <div class="col-755">
                            <textarea id="subject" name="body" placeholder="Body" style="height:200px"></textarea>
                          </div>
                        </div>
                        <div class="row">
                          <input type="submit" value="Submit">
                        </div>
                        </form>
                      </div>              
              </div>
        </div>
        </div>
      </div>



   
    

    <script>
        var x, i, j, l, ll, selElmnt, a, b, c;
        /*look for any elements with the class "custom-select":*/
        x = document.getElementsByClassName("custom-select");
        l = x.length;
        for (i = 0; i < l; i++) {
          selElmnt = x[i].getElementsByTagName("select")[0];
          ll = selElmnt.length;
          /*for each element, create a new DIV that will act as the selected item:*/
          a = document.createElement("DIV");
          a.setAttribute("class", "select-selected");
          a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
          x[i].appendChild(a);
          /*for each element, create a new DIV that will contain the option list:*/
          b = document.createElement("DIV");
          b.setAttribute("class", "select-items select-hide");
          for (j = 1; j < ll; j++) {
            /*for each option in the original select element,
            create a new DIV that will act as an option item:*/
            c = document.createElement("DIV");
            c.innerHTML = selElmnt.options[j].innerHTML;
            c.addEventListener("click", function(e) {
                /*when an item is clicked, update the original select box,
                and the selected item:*/
                var y, i, k, s, h, sl, yl;
                s = this.parentNode.parentNode.getElementsByTagName("select")[0];
                sl = s.length;
                h = this.parentNode.previousSibling;
                for (i = 0; i < sl; i++) {
                  if (s.options[i].innerHTML == this.innerHTML) {
                    s.selectedIndex = i;
                    h.innerHTML = this.innerHTML;
                    y = this.parentNode.getElementsByClassName("same-as-selected");
                    yl = y.length;
                    for (k = 0; k < yl; k++) {
                      y[k].removeAttribute("class");
                    }
                    this.setAttribute("class", "same-as-selected");
                    break;
                  }
                }
                h.click();
            });
            b.appendChild(c);
          }
          x[i].appendChild(b);
          a.addEventListener("click", function(e) {
              /*when the select box is clicked, close any other select boxes,
              and open/close the current select box:*/
              e.stopPropagation();
              closeAllSelect(this);
              this.nextSibling.classList.toggle("select-hide");
              this.classList.toggle("select-arrow-active");
            });
        }
        function closeAllSelect(elmnt) {
          /*a function that will close all select boxes in the document,
          except the current select box:*/
          var x, y, i, xl, yl, arrNo = [];
          x = document.getElementsByClassName("select-items");
          y = document.getElementsByClassName("select-selected");
          xl = x.length;
          yl = y.length;
          for (i = 0; i < yl; i++) {
            if (elmnt == y[i]) {
              arrNo.push(i)
            } else {
              y[i].classList.remove("select-arrow-active");
            }
          }
          for (i = 0; i < xl; i++) {
            if (arrNo.indexOf(i)) {
              x[i].classList.add("select-hide");
            }
          }
        }
        /*if the user clicks anywhere outside the select box,
        then close all select boxes:*/
        document.addEventListener("click", closeAllSelect);
        </script>
        

</body>
</html>

app/templates/edit_form.html
<!DOCTYPE html>
<html>
  <title>Edit Note</title>
  
  <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
  <body>
        
{% block body %}

  

<div class="column1" >
  <div class="second">
      <form method="POST" action="{{ url_for('notes.edit_note',e_id=note.minute_id) }}">
        
        <div class="row">
          <div class="col-755">
            <div>{{ form.title.label }} {{ form.title() }}</div>
          </div>
        </div>
        <div class="row">
          <div class="col-755">
            <div>{{ form.purpose.label }} {{ form.purpose() }}</div>
          </div>
        </div>
        <div class="row">
          <div class="col-755">
            <div>{{ form.name_of_org.label }} {{ form.name_of_org() }}</div>
          </div>
        </div>
        <div class="row">
          <div class="col-755">
            <div>{{ form.attendees.label }} {{ form.attendees() }}</div>
          </div>
        </div>
        <div class="row">
          <div class="col-755">
            <div>{{ form.body.label }} {{ form.body() }}</div>
          </div>
        </div>
        <div class="row" style="padding-top: 5px;">
          <input type="submit" value="Submit">
        </div>

      </form>
      
  </div>
  <form action="/dashboard" style="padding-top: 15px;">
    <button type="submit" style="width: 200px;  height: 50px;background: #FFFFFF;border-radius: 30px;">Dashboard</button> 
</form>
</div>


{% endblock %}
      
  
</body>
</html>
    
    

app/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}

<div class="box">
  <div>
      <p>Capture, track, and organize meeting notes conveniently.</p>
  </div>
</div>


{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="form-section">
  <form class="forms" action="/login" method="POST">
      
      <div class="row">
        
        <div class="col-75">
          <input type="text" id="lname" name="username" placeholder="username">
        </div>
      </div>
      <div class="row">
        
              <div class="col-75">
                <input style="height: 50px; width: 180%; margin-top: 18px;" type="password" id="lname" name="password" placeholder="     password">
              </div>
            </div>
            
      <div>
          <p class="submit-p">No account? <a href="/signup"> Sign up</a></p>
         
      </div>

      <div class="row">
        <input type="submit" value="Submit">
      </div>
      </form>
</div>
{% endblock %}
     

app/templates/note.html
<!DOCTYPE html>
<html>
    <body style="background-color: #5DEBE2; width: 1440px; height: 900px;">
        
        <div class="box" style="background-color: #5DEBE2; position: relative;">
            <div style="display: flex; flex-direction: column; align-self: center; margin-left: 65px; margin-right: 65px; margin-top: 65px; margin-bottom: 89px; background-color:white;">
                {% block body %}
                <h1 style="padding-top: 5px; padding-left: 5px;">Title: {{ note.title }}</h1>
                <h3 style="padding-right: 5px; padding-left: 5px;">Purpose: {{ note.purpose }}</h3>
                <h3 style="padding-right: 5px; padding-left: 5px;">Organisation: {{ note.organisation }}</h3>
                <p style="padding-right: 5px; padding-left: 5px;"><h3 style="padding-right: 5px; padding-left: 5px;">The content:</h3> {{note.body}} </p>
                <h3 style="padding-right: 5px; padding-left: 5px;">People who attended: {{ note.attendees }}</h3>
                <h3 style="padding-right: 5px; padding-left: 5px;">Written by: {{ note.full_name }}</h3>
                <h3 style="padding-right: 5px; padding-left: 5px;">Date created: {{ create }} </h3>
                <h3 style="padding-right: 5px; padding-left: 5px;">Date modified: {{ modified }}</h3>


                {% endblock %} 
            </div>
        </div>
        
        <div style="padding-left: 645px;">
            <form action="/dashboard">
                <button type="submit" style="width: 200px; height: 50px;background: #FFFFFF;border-radius: 30px;">Dashboard</button> 
            </form>
            <form action="{{ url_for('notes.edit_note',e_id=note.minute_id) }}">
                <button type="submit" style="width: 200px;height: 50px;background: #FFFFFF;border-radius: 30px;">Edit</button>
            </form>
            <form action="{{ url_for('notes.delete_note',d_id=note.minute_id) }}">
                <button type="submit" style="width: 200px;height: 50px;background: #FFFFFF;border-radius: 30px;">Delete</button>
            </form>
        </div>
        
    </body>
</html>

app/templates/results.html
<!DOCTYPE HTML>
<html>
<head>
        <title>Dashboard</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
   

</head>
<body>

    <div id="app">
	<nav>
     <ul class="menu">
         <li class="logo"> <a><img src="/static/images/ANALOG.png"/></a> </li>
         <li class="item button"> <a href="/logout"><img style="width: 34px;" src="/static/images/human.png"></a>  </li>
     </ul>  
    </nav>

    <div class="row">
        <div class="column">



<div style="background-color: #5DEBE2; padding: 10px; margin-top: 34px;">
        <div class="second">
                
          <div class="row">
            {% for note in notes %}
            <div class="col-75" style="background-color: white;">
              
              <div><p>Title: {{ note.title }} <br>Purpose: {{ note.purpose }} <br> Written by: {{ note.full_name }}</p></div>
              <br>
              <p><a type="button" href="{{ url_for('notes.view_note',n_id=note.minute_id) }}">View</a>   <a href="/edit/<note.id>">Edit</a>   <a href="{{ url_for('notes.delete_note',d_id=note.minute_id) }}">Delete</a></p>
            </div>
            {% endfor %}
          </div>
          
        </div> 
                   
</div>
<form action="/dashboard" style="margin-top: 20px;" >
    <button type="submit" style="width: 200px; height: 50px;background: #FFFFFF;border-radius: 30px;">Dashboard</button> 
</form>  

        </div>
        <div class="column" >
            <div class="second">
                    <form action="{{ url_for('home.handle_data') }}" method="post">
                        <div class="row">
                          <div class="col-755">
                            <input type="text" id="fname" name="title" placeholder="Title">
                          </div>
                        </div>
                        <div class="row">
                          
                          <div class="col-755">
                            <input type="text" id="lname" name="purpose" placeholder="Purpose">
                          </div>
                        </div>
                        <div class="row">
                          
                                <div class="col-755">
                                  <input type="text" id="lname" name="name_of_org" placeholder="organisation">
                                </div>
                              </div>
                              <div class="row">
                          
                                    <div class="col-755">
                                      <input type="text" id="lname" name="attendees" placeholder="Attendees">
                                    </div>
                                  </div>
                        <div class="row">
                          
                          <div class="col-755">
                            <textarea id="subject" name="body" placeholder="Body" style="height:200px"></textarea>
                          </div>
                        </div>
                        <div class="row">
                          <input type="submit" value="Submit">
                        </div>
                        </form>
                      </div>              
              </div>
        </div>
        </div>
      </div>



   
    

    <script>
        var x, i, j, l, ll, selElmnt, a, b, c;
        /*look for any elements with the class "custom-select":*/
        x = document.getElementsByClassName("custom-select");
        l = x.length;
        for (i = 0; i < l; i++) {
          selElmnt = x[i].getElementsByTagName("select")[0];
          ll = selElmnt.length;
          /*for each element, create a new DIV that will act as the selected item:*/
          a = document.createElement("DIV");
          a.setAttribute("class", "select-selected");
          a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
          x[i].appendChild(a);
          /*for each element, create a new DIV that will contain the option list:*/
          b = document.createElement("DIV");
          b.setAttribute("class", "select-items select-hide");
          for (j = 1; j < ll; j++) {
            /*for each option in the original select element,
            create a new DIV that will act as an option item:*/
            c = document.createElement("DIV");
            c.innerHTML = selElmnt.options[j].innerHTML;
            c.addEventListener("click", function(e) {
                /*when an item is clicked, update the original select box,
                and the selected item:*/
                var y, i, k, s, h, sl, yl;
                s = this.parentNode.parentNode.getElementsByTagName("select")[0];
                sl = s.length;
                h = this.parentNode.previousSibling;
                for (i = 0; i < sl; i++) {
                  if (s.options[i].innerHTML == this.innerHTML) {
                    s.selectedIndex = i;
                    h.innerHTML = this.innerHTML;
                    y = this.parentNode.getElementsByClassName("same-as-selected");
                    yl = y.length;
                    for (k = 0; k < yl; k++) {
                      y[k].removeAttribute("class");
                    }
                    this.setAttribute("class", "same-as-selected");
                    break;
                  }
                }
                h.click();
            });
            b.appendChild(c);
          }
          x[i].appendChild(b);
          a.addEventListener("click", function(e) {
              /*when the select box is clicked, close any other select boxes,
              and open/close the current select box:*/
              e.stopPropagation();
              closeAllSelect(this);
              this.nextSibling.classList.toggle("select-hide");
              this.classList.toggle("select-arrow-active");
            });
        }
        function closeAllSelect(elmnt) {
          /*a function that will close all select boxes in the document,
          except the current select box:*/
          var x, y, i, xl, yl, arrNo = [];
          x = document.getElementsByClassName("select-items");
          y = document.getElementsByClassName("select-selected");
          xl = x.length;
          yl = y.length;
          for (i = 0; i < yl; i++) {
            if (elmnt == y[i]) {
              arrNo.push(i)
            } else {
              y[i].classList.remove("select-arrow-active");
            }
          }
          for (i = 0; i < xl; i++) {
            if (arrNo.indexOf(i)) {
              x[i].classList.add("select-hide");
            }
          }
        }
        /*if the user clicks anywhere outside the select box,
        then close all select boxes:*/
        document.addEventListener("click", closeAllSelect);
        </script>
        

</body>
</html>

app/templates/signup.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block body %}
<div class="form-section">
  <form class="forms" method="POST">
      <div class="row">
        <div class="col-75">
          <input type="text" id="fname" name="full_name" placeholder="fullname">
        </div>
      </div>
      <div class="row">
        <div class="col-75">
          <input style="height: 50px; width: 180%; margin-top: 18px;" type="email" id="fname" name="email" placeholder="email">
        </div>
      </div>
      <div class="row">
        
        <div class="col-75">
          <input type="text" id="lname" name="username" placeholder="username">
        </div>
      </div>
      <div class="row">
        
        <div class="col-75">
          <input type="text" id="lname" name="position" placeholder="Position">
        </div>
      </div>
      <div class="row">
        
              <div class="col-75">
                <input style="height: 50px; width: 180%; margin-top: 18px;" min="8" type="password"  id="lname" name="password" placeholder="password">
              </div>
            </div>
            <div class="row">
        
                  <div class="col-75">
                    <input style="height: 50px; width: 180%; margin-top: 18px;" min="8" type="password" id="lname" name="confirm_password" placeholder="      confirm password">
                  </div>
                </div>
      <div>
          <p class="submit-p">Already have an account? <a href="/login"> Log in</a> </p>
      </div>

      <div class="row">
        <input type="submit" value="Submit">
      </div>
      </form>
</div>
{% endblock %}